version: '3'

services:
  dump1090:
    env_file: '.env'
    build: ./dump1090-fa
    ports:
      - 30005:30005
      - 80:80
    devices:
      - /dev/bus/usb
    restart: unless-stopped

  modesmixer2:
    env_file: '.env'
    environment:
      - 'MM2_INPUT=dump1090:30005 adsbexchange:30105'
      - 'MM2_WEBPORT=8080'
    build: ./modesmixer2
    ports:
      - 8080:8080
    volumes:
      - ./modesmixer2/distances.json:/distances.json
    depends_on:
      - dump1090
      - adsbexchange
    restart: on-failure
    
  fr24:
    env_file: '.env'
    environment:
      - 'DUMP1090_HOST=dump1090'
    depends_on:
      - dump1090
    build: ./fr24feed
    restart: on-failure

  pf:
    env_file: '.env'
    environment:
      - 'DUMP1090_HOST=dump1090'
    depends_on:
      - dump1090
    build: ./pffeed
    ports:
      - 30053:30053
    restart: on-failure

  adsbexchange:
    image: mikenye/adsbexchange
    depends_on:
      - dump1090
    ports:
      - 30105:30105
    restart: on-failure
    environment:
      - SITENAME=ADSB_Receiver
      - BEASTHOST=dump1090
      - TZ=${RECEIVER_TIMEZONE}
      - LAT=${RECEIVER_LATITUDE}
      - LONG=${RECEIVER_LONGITUDE}
      - ALT=${RECEIVER_ALTITUDE}
      - UUID=${ADSBX_UUID}
