name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron:  '17 8 * * 6'
jobs:
  build-dump1090:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build ./dump1090-fa --tag my-image-name:$(date +%s)
  build-modesmixer2:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build ./modesmixer2 --tag my-image-name:$(date +%s)
  build-fr24:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build ./fr24feed --tag my-image-name:$(date +%s)
  build-pf:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build ./pffeed --tag my-image-name:$(date +%s)
